import { LibraryMeal } from './meals';

export const mealLibrarySeed: LibraryMeal[] = [
  {
    id: 'lib-power-eggs-bowl',
    name: 'Power Eggs Bowl',
    description: '3 eggs · avocado · sourdough · spinach',
    macros: { protein: 24, fat: 22, carb: 30, fiber: 6 },
    anchor: '3 eggs · scrambled or over-easy',
    build: ['Sourdough toast', 'Half avocado', 'Sautéed spinach'],
    complete: ['Cracked pepper', 'Hot sauce'],
  },
  {
    id: 'lib-chicken-power-plate',
    name: 'Chicken Power Plate',
    description: 'Grilled chicken · brown rice · roasted veg',
    macros: { protein: 38, fat: 8, carb: 42, fiber: 5 },
    anchor: 'Grilled chicken breast (~5 oz)',
    build: ['Brown rice', 'Roasted broccoli + carrots'],
    complete: ['Olive oil drizzle', 'Squeeze of lemon'],
  },
  {
    id: 'lib-greek-yogurt-stack',
    name: 'Greek Yogurt Stack',
    description: 'Greek yogurt · berries · walnuts · honey',
    macros: { protein: 22, fat: 14, carb: 24, fiber: 4 },
    anchor: 'Plain Greek yogurt (~1 cup)',
    build: ['Mixed berries', 'Crushed walnuts'],
    complete: ['Drizzle of honey', 'Dash of cinnamon'],
  },
  {
    id: 'lib-salmon-and-greens',
    name: 'Salmon & Greens',
    description: 'Salmon · sweet potato · asparagus',
    macros: { protein: 32, fat: 18, carb: 28, fiber: 6 },
    anchor: 'Grilled salmon (~5 oz)',
    build: ['Roasted sweet potato', 'Charred asparagus'],
    complete: ['Lemon wedge', 'Fresh dill'],
  },
  {
    id: 'lib-turkey-lettuce-wraps',
    name: 'Turkey Lettuce Wraps',
    description: 'Ground turkey · butter lettuce · avocado · tomato',
    macros: { protein: 28, fat: 14, carb: 8, fiber: 4 },
    anchor: 'Ground turkey (~5 oz)',
    build: ['Butter lettuce cups', 'Sliced avocado', 'Diced tomato'],
    complete: ['Lime juice', 'Fresh cilantro'],
  },
  {
    id: 'lib-protein-smoothie',
    name: 'Protein Smoothie',
    description: 'Whey · banana · spinach · almond butter',
    macros: { protein: 30, fat: 10, carb: 32, fiber: 5 },
    anchor: 'Whey protein scoop',
    build: ['Frozen banana', 'Handful of spinach', 'Spoon of almond butter', 'Oat milk'],
    complete: ['Cinnamon', 'Splash of vanilla'],
  },
  {
    id: 'lib-beef-and-sweet-potato',
    name: 'Beef & Sweet Potato',
    description: 'Lean ground beef · sweet potato · broccoli',
    macros: { protein: 34, fat: 18, carb: 30, fiber: 6 },
    anchor: 'Lean ground beef (~5 oz)',
    build: ['Roasted sweet potato', 'Steamed broccoli'],
    complete: ['Roasted garlic', 'Flaky sea salt'],
  },
  {
    id: 'lib-chickpea-power-bowl',
    name: 'Chickpea Power Bowl',
    description: 'Chickpeas · quinoa · greens · tahini',
    macros: { protein: 18, fat: 14, carb: 42, fiber: 10 },
    anchor: 'Chickpeas (~1 cup)',
    build: ['Cooked quinoa', 'Mixed greens', 'Sliced cucumber'],
    complete: ['Tahini drizzle', 'Squeeze of lemon'],
  },
];
