// lib/programContent.ts
//
// Authored content for all 12 weeks of CREATE POWER, from Karen's
// canonical 12-Week Curriculum Map + V2 Actions Tracker (Dec 2025
// corrected revision). Slide notes are paraphrased to remove em dashes
// per the no-em-dash project memory. Weekly targets are derived from
// the per-block "Block Target" in the Actions Tracker PDF, divided by 2.

import type { Block, Week } from './program';

export const BLOCKS: readonly Block[] = [
  {
    blockId: 'COMMIT',
    weekRange: [1, 2],
    mindset:
      "You're building the foundation for everything that follows. Showing up at 40 to 50% beats optimizing at 0%. Begin noticing how small choices connect to bigger outcomes. This is the start of systems thinking.",
    consistencyTarget: '40 to 50%',
    powerCompass: {
      P: { role: 'PRIMARY', note: 'Spot patterns and triggers' },
      O: { role: 'SECONDARY', note: 'Small consistent steps' },
      W: { role: 'PRIMARY', note: 'Sugar, whole foods, move' },
      E: { role: 'MAINTAIN', note: 'Just notice energy peaks' },
      R: { role: 'MAINTAIN', note: 'Consistent bedtime' },
    },
  },
  {
    blockId: 'REFINE',
    weekRange: [3, 4],
    mindset:
      'Motivation will likely dip around Week 3. That is expected and temporary. Refusing to quit matters more than optimizing. This is where you start designing your first systems by making healthy choices the default through environment setup, meal prep, and scheduling.',
    consistencyTarget: '50 to 60%',
    powerCompass: {
      P: { role: 'SECONDARY', note: 'TEB loop: pause before reacting' },
      O: { role: 'PRIMARY', note: 'Design your environment for success' },
      W: { role: 'PRIMARY', note: 'ABC Power Meals, eat to 80% full' },
      E: { role: 'MAINTAIN', note: 'Keep noticing energy patterns' },
      R: { role: 'SECONDARY', note: 'Wind down routine, expect the dip' },
    },
  },
  {
    blockId: 'EVOLVE',
    weekRange: [5, 6],
    mindset:
      "Skills are becoming automatic. Notice: this is just who you are now. Your general habits are ready to become specific personal systems. How you prep food, when you train, what your rest routine looks like, step by step.",
    consistencyTarget: '60 to 70%',
    powerCompass: {
      P: { role: 'PRIMARY', note: 'Pattern skills in social settings' },
      O: { role: 'PRIMARY', note: 'Identity shift: I am someone who' },
      W: { role: 'SECONDARY', note: 'ABC Power Meals as default; eating to 80%' },
      E: { role: 'SECONDARY', note: 'Three accounts: end of day audit' },
      R: { role: 'MAINTAIN', note: 'Sleep environment, keep what REFINE built' },
    },
  },
  {
    blockId: 'ADAPT',
    weekRange: [7, 8],
    mindset:
      "Stress tests your systems. That is useful data, not failure. Stress reveals which systems hold and which need to flex. What needs to bend while keeping your foundation solid? This block is about discovering you're stronger for it.",
    consistencyTarget: '70 to 80%',
    powerCompass: {
      P: { role: 'PRIMARY', note: 'Recognize the need behind the pattern' },
      O: { role: 'SECONDARY', note: 'Own setbacks, bare minimum protocols' },
      W: { role: 'MAINTAIN', note: 'Flexible consistency, best options' },
      E: { role: 'SECONDARY', note: 'Emotional energy, boundaries' },
      R: { role: 'PRIMARY', note: 'Box breathing, build antifragility' },
    },
  },
  {
    blockId: 'THRIVE',
    weekRange: [9, 10],
    mindset:
      "You're not trying anymore. This is how you live. Document the systems that are working. If you can describe it, you can repeat it. Your actions from here forward are self directed. Choose what matters most for your continued growth.",
    consistencyTarget: '80% and up',
    powerCompass: {
      P: { role: 'PRIMARY', note: 'Create your personal pattern guide' },
      O: { role: 'PRIMARY', note: 'Reflect on your identity transformation' },
      W: { role: 'SECONDARY', note: 'Optimize workout nutrition' },
      E: { role: 'SECONDARY', note: 'Three accounts: physical, intellectual, emotional' },
      R: { role: 'SECONDARY', note: 'Fine tune protocols, know your stress signals' },
    },
  },
  {
    blockId: 'EXCEL',
    weekRange: [11, 12],
    mindset:
      "This isn't the end. It's the foundation for your next chapter. Your systems are your lifestyle now. What you've built continues beyond this program. Take time to celebrate how far you've come and plan what comes next.",
    consistencyTarget: '80% and up',
    powerCompass: {
      P: { role: 'PRIMARY', note: 'Celebrate mastery, document what works' },
      O: { role: 'SECONDARY', note: 'Small consistent steps' },
      W: { role: 'MAINTAIN', note: 'Nutrition and strength are your lifestyle' },
      E: { role: 'PRIMARY', note: 'Document your energy routines' },
      R: { role: 'PRIMARY', note: 'Complete resilience toolkit, antifragility lived' },
    },
  },
];

export const WEEKS: readonly Week[] = [
  {
    weekNumber: 1,
    blockId: 'COMMIT',
    title: 'Week 1: Awareness and First Steps',
    primaryFocus: 'Identify your stuck patterns and choose a nutrition track.',
    slideNotes: [
      'Welcome to Week 1. Here is what to expect.',
      'The 5 Universal Patterns. Which one is yours?',
      'Two Nutrition Tracks explained: Blood Sugar versus Processed Food.',
      'Seventy percent consistency beats one hundred percent perfection.',
      'Sleep foundation. Pick your bedtime.',
      "This week's actions in a simple checklist.",
    ],
    weekAtAGlance: [
      { id: 'w1-notice-patterns', label: 'Notice and name one pattern today', thread: 'P', weeklyTarget: 7 },
      { id: 'w1-nutrition-track', label: 'Choose your nutrition track for today', thread: 'W', weeklyTarget: 7 },
      { id: 'w1-workout', label: 'Strength workout', thread: 'W', weeklyTarget: 2 },
      { id: 'w1-walk', label: 'Walk', thread: 'W', weeklyTarget: 3 },
      { id: 'w1-bedtime', label: 'Bedtime within 30 minutes of plan', thread: 'R', weeklyTarget: 5 },
    ],
    toolSlugs: ['five-universal-patterns', 'nutrition-track-chooser'],
    discussionPrompt: 'Which pattern did you identify as your main one? Share with the group.',
  },
  {
    weekNumber: 2,
    blockId: 'COMMIT',
    title: 'Week 2: Building Momentum',
    primaryFocus: 'Add the second nutrition track. Movement for energy. Sleep environment.',
    slideNotes: [
      'Week 2. You made it through Week 1.',
      'Adding the second nutrition track.',
      'Movement breaks for energy. Five minutes is high ROI.',
      'Sleep environment basics.',
      'Stacking without dropping.',
      'A note about Weeks 3 and 4: the motivation dip is coming. Prepare now.',
    ],
    weekAtAGlance: [
      { id: 'w2-both-tracks', label: 'Use both nutrition tracks today', thread: 'W', weeklyTarget: 7 },
      { id: 'w2-movement-break', label: 'One movement break today', thread: 'W', weeklyTarget: 5 },
      { id: 'w2-workout', label: 'Strength workout', thread: 'W', weeklyTarget: 2 },
      { id: 'w2-walk', label: 'Walk', thread: 'W', weeklyTarget: 3 },
      { id: 'w2-energy-notice', label: 'Notice how your energy feels today', thread: 'E', weeklyTarget: 7 },
      { id: 'w2-bedtime', label: 'Bedtime within 30 minutes of plan', thread: 'R', weeklyTarget: 5 },
      { id: 'w2-sleep-env', label: 'One sleep environment tweak today', thread: 'R', weeklyTarget: 5 },
    ],
    toolSlugs: ['movement-breaks-menu', 'sleep-environment-checklist'],
    discussionPrompt: "What's one thing that's already feeling easier than Day 1?",
  },
  {
    weekNumber: 3,
    blockId: 'REFINE',
    title: 'Week 3: Environment Design',
    primaryFocus: 'Design your environment for success. Whole protein emphasis.',
    slideNotes: [
      'Welcome to the dip. This is normal.',
      'Why environment beats willpower. A short neuroscience note.',
      'Kitchen Environment Reset. Plan 30 to 45 minutes.',
      'Workout environment setup.',
      'ABC Power Meals. Protein prioritization.',
      'Your systems carry you when motivation drops.',
    ],
    weekAtAGlance: [
      { id: 'w3-kitchen-reset', label: 'One kitchen reset action today', thread: 'O', weeklyTarget: 5 },
      { id: 'w3-abc-meal', label: 'Build one ABC Power Meal today', thread: 'W', weeklyTarget: 7 },
      { id: 'w3-workout', label: 'Strength workout', thread: 'W', weeklyTarget: 3 },
      { id: 'w3-walk', label: 'Walk', thread: 'W', weeklyTarget: 4 },
      { id: 'w3-energy-notice', label: 'Notice how your energy feels today', thread: 'E', weeklyTarget: 7 },
      { id: 'w3-bedtime', label: 'Bedtime within 30 minutes of plan', thread: 'R', weeklyTarget: 5 },
    ],
    toolSlugs: ['kitchen-reset-guide', 'abc-power-meals-guide'],
    discussionPrompt: 'Post a photo of your kitchen reset (fridge, pantry, or workout space).',
  },
  {
    weekNumber: 4,
    blockId: 'REFINE',
    title: 'Week 4: The Pause Practice',
    primaryFocus: 'Notice, pause, observe. Wind down routine.',
    slideNotes: [
      "You survived the hardest week. You're a dip survivor.",
      'The Pause Practice: Notice, Pause, Observe.',
      'Creating space before reacting. Not changing yet.',
      'Boundary conversations. Asking for what you need.',
      'Wind down routine introduction.',
      "Week 5 is where things get easier. You're building the base.",
    ],
    weekAtAGlance: [
      { id: 'w4-pause-practice', label: 'Pause practice when a trigger lands', thread: 'P', weeklyTarget: 5 },
      { id: 'w4-boundary', label: 'One boundary conversation this week', thread: 'O', weeklyTarget: 1 },
      { id: 'w4-abc-meal', label: 'Build one ABC Power Meal today', thread: 'W', weeklyTarget: 7 },
      { id: 'w4-workout', label: 'Strength workout', thread: 'W', weeklyTarget: 3 },
      { id: 'w4-walk', label: 'Walk', thread: 'W', weeklyTarget: 4 },
      { id: 'w4-wind-down', label: 'Wind down routine before bed', thread: 'R', weeklyTarget: 5 },
      { id: 'w4-bedtime', label: 'Bedtime within 30 minutes of plan', thread: 'R', weeklyTarget: 5 },
    ],
    toolSlugs: ['pause-practice-guide', 'wind-down-routine-builder'],
    discussionPrompt: 'What does your wind down routine look like? Share what you are trying.',
  },
  {
    weekNumber: 5,
    blockId: 'EVOLVE',
    title: 'Week 5: TEB Loop and Meal Prep',
    primaryFocus: 'TEB Loop. Identity statements. Meal prep system.',
    slideNotes: [
      'Things should feel easier now. Acknowledge progress.',
      'TEB Loop: Thinking, Emotion, Behavior.',
      'Let thinking drive your behavior, not emotion.',
      'Identity statements. I am someone who.',
      'Meal Prep System. Ninety minutes equals a week of easy choices.',
      "You're evolving from trying to being.",
    ],
    weekAtAGlance: [
      { id: 'w5-teb', label: 'TEB practice when a pattern shows up', thread: 'P', weeklyTarget: 5 },
      { id: 'w5-identity', label: 'Read and apply your identity statement', thread: 'O', weeklyTarget: 7 },
      { id: 'w5-meal-prep', label: 'Meal prep session', thread: 'W', weeklyTarget: 1 },
      { id: 'w5-abc-meal', label: 'Build ABC Power Meals today', thread: 'W', weeklyTarget: 7 },
      { id: 'w5-workout', label: 'Strength workout', thread: 'W', weeklyTarget: 3 },
      { id: 'w5-walk', label: 'Walk', thread: 'W', weeklyTarget: 4 },
      { id: 'w5-bedtime', label: 'Bedtime within 30 minutes of plan', thread: 'R', weeklyTarget: 6 },
    ],
    toolSlugs: ['teb-loop-guide', 'meal-prep-system-guide'],
    discussionPrompt: 'Complete this: I am someone who __________. Share your identity statement.',
  },
  {
    weekNumber: 6,
    blockId: 'EVOLVE',
    title: 'Week 6: Social Navigation',
    primaryFocus: 'Social pattern navigation. Anti inflammatory focus. Movement snacks.',
    slideNotes: [
      "Halfway there. What's automatic now?",
      'Social situations: parties, dinners, sabotage.',
      'Using TEB in complex environments.',
      'Anti inflammatory foods. Colorful vegetables.',
      'Movement snacks. Thirty second micro movements.',
      'Recovery assessment. Good soreness versus bad pain.',
    ],
    weekAtAGlance: [
      { id: 'w6-social-nav', label: 'Navigate one social situation with TEB', thread: 'P', weeklyTarget: 2 },
      { id: 'w6-identity', label: 'Read and apply your identity statement', thread: 'O', weeklyTarget: 7 },
      { id: 'w6-movement-snack', label: 'Three or more movement snacks today', thread: 'W', weeklyTarget: 5 },
      { id: 'w6-workout', label: 'Strength workout', thread: 'W', weeklyTarget: 3 },
      { id: 'w6-walk', label: 'Walk', thread: 'W', weeklyTarget: 4 },
      { id: 'w6-energy-audit', label: 'End of day audit: gains and drains', thread: 'E', weeklyTarget: 5 },
      { id: 'w6-bedtime', label: 'Bedtime within 30 minutes of plan', thread: 'R', weeklyTarget: 6 },
    ],
    toolSlugs: ['social-situations-playbook', 'movement-snacks-menu'],
    discussionPrompt: 'What social situation did you navigate this week? How did it go?',
  },
  {
    weekNumber: 7,
    blockId: 'ADAPT',
    title: 'Week 7: Stress Tools',
    primaryFocus: 'Box breathing. Recognize stress signals. Non food stress relief.',
    slideNotes: [
      "Life will test you. Let's prepare.",
      'Box Breathing: 4 4 4 4 technique.',
      'When patterns intensify under stress.',
      'Recognizing your stress signals.',
      'Non food stress relief options.',
      'A preview of what to do when everything falls apart.',
    ],
    weekAtAGlance: [
      { id: 'w7-breathing-am', label: 'Box breathing in the morning', thread: 'R', weeklyTarget: 7 },
      { id: 'w7-breathing-pm', label: 'Box breathing in the evening', thread: 'R', weeklyTarget: 7 },
      { id: 'w7-stress-signal', label: 'Name one stress signal today', thread: 'P', weeklyTarget: 5 },
      { id: 'w7-non-food', label: 'Use one non food stress relief option', thread: 'P', weeklyTarget: 5 },
      { id: 'w7-workout', label: 'Strength workout', thread: 'W', weeklyTarget: 3 },
      { id: 'w7-walk', label: 'Walk', thread: 'W', weeklyTarget: 4 },
      { id: 'w7-bedtime', label: 'Bedtime within 30 minutes of plan', thread: 'R', weeklyTarget: 6 },
    ],
    toolSlugs: ['box-breathing-guide', 'non-food-stress-relief-menu'],
    discussionPrompt: 'What are your early stress signals? How does your body tell you?',
  },
  {
    weekNumber: 8,
    blockId: 'ADAPT',
    title: 'Week 8: Bare Minimum Protocol',
    primaryFocus: 'Crisis protocol. Flexible consistency. Integration check.',
    slideNotes: [
      'Bare Minimum Protocol. Your crisis plan.',
      "What counts when everything's falling apart.",
      'Flexible consistency versus rigid perfection.',
      'Mid program integration check.',
      'What is working? What needs adjustment?',
      'A preview of Weeks 9 and 10. Automaticity begins.',
    ],
    weekAtAGlance: [
      { id: 'w8-protocol-created', label: 'Bare minimum protocol drafted', thread: 'R', weeklyTarget: 1 },
      { id: 'w8-protocol-applied', label: 'Apply protocol on a hard day', thread: 'R', weeklyTarget: 2 },
      { id: 'w8-integration', label: 'Integration reflection today', thread: 'O', weeklyTarget: 3 },
      { id: 'w8-workout', label: 'Strength workout', thread: 'W', weeklyTarget: 3 },
      { id: 'w8-walk', label: 'Walk', thread: 'W', weeklyTarget: 4 },
      { id: 'w8-energy-audit', label: 'End of day audit: gains and drains', thread: 'E', weeklyTarget: 5 },
      { id: 'w8-bedtime', label: 'Bedtime within 30 minutes of plan', thread: 'R', weeklyTarget: 6 },
    ],
    toolSlugs: ['bare-minimum-protocol-builder'],
    discussionPrompt: "What's your bare minimum when life gets hard? Share your protocol.",
  },
  {
    weekNumber: 9,
    blockId: 'THRIVE',
    title: 'Week 9: Automaticity Audit',
    primaryFocus: 'What is automatic now? Advanced sleep optimization. Energy ROI.',
    slideNotes: [
      "What's automatic now versus Week 1?",
      'Automaticity Audit. Where are you?',
      'Advanced sleep optimization.',
      'Stress signal mastery.',
      'Energy management. ROI thinking.',
      'Systems are running. Trust them.',
    ],
    weekAtAGlance: [
      { id: 'w9-automaticity', label: 'Name one habit that is now automatic', thread: 'O', weeklyTarget: 5 },
      { id: 'w9-energy-roi', label: 'One energy ROI choice today', thread: 'E', weeklyTarget: 5 },
      { id: 'w9-workout', label: 'Strength workout', thread: 'W', weeklyTarget: 3 },
      { id: 'w9-walk', label: 'Walk', thread: 'W', weeklyTarget: 4 },
      { id: 'w9-stress-signal', label: 'Track one stress signal today', thread: 'R', weeklyTarget: 5 },
      { id: 'w9-bedtime', label: 'Bedtime within 30 minutes of plan', thread: 'R', weeklyTarget: 6 },
    ],
    toolSlugs: ['automaticity-audit', 'stress-signal-identifier'],
    discussionPrompt: 'What habit that was hard in Week 1 is now automatic?',
  },
  {
    weekNumber: 10,
    blockId: 'THRIVE',
    title: 'Week 10: Energy Orchestra',
    primaryFocus: 'Three energy accounts. Antifragility system. System documentation.',
    slideNotes: [
      'Your daily energy flow. Morning, midday, evening.',
      'Energy Orchestra. All routines working together.',
      'Three energy accounts: physical, intellectual, emotional.',
      "Documentation. What's your personal system?",
      'Recovery. When to push versus rest.',
      'Two weeks left. Celebration planning.',
    ],
    weekAtAGlance: [
      { id: 'w10-energy-plan', label: 'Run your morning, midday, evening plan', thread: 'E', weeklyTarget: 7 },
      { id: 'w10-three-accounts', label: 'Audit all three energy accounts today', thread: 'E', weeklyTarget: 5 },
      { id: 'w10-document', label: 'Document one piece of your system', thread: 'O', weeklyTarget: 5 },
      { id: 'w10-workout', label: 'Strength workout', thread: 'W', weeklyTarget: 3 },
      { id: 'w10-walk', label: 'Walk', thread: 'W', weeklyTarget: 4 },
      { id: 'w10-bedtime', label: 'Bedtime within 30 minutes of plan', thread: 'R', weeklyTarget: 6 },
    ],
    toolSlugs: ['energy-orchestra-planner', 'my-system-documentation'],
    discussionPrompt: 'What would you tell Week 1 you about this journey?',
  },
  {
    weekNumber: 11,
    blockId: 'EXCEL',
    title: 'Week 11: Pattern Maintenance System',
    primaryFocus: 'Pattern maintenance. Energy Orchestra refinement.',
    slideNotes: [
      "Your pattern mastery. What's conquered?",
      'Pattern maintenance. Staying aware for life.',
      'Applying pattern skills to all life areas.',
      'Your unique rhythm. What works for you.',
      "Crowding out. What's naturally gone?",
      'A preview of Week 12. Celebration and what is next.',
    ],
    weekAtAGlance: [
      { id: 'w11-pattern-maint', label: 'Pattern maintenance check today', thread: 'P', weeklyTarget: 5 },
      { id: 'w11-energy-plan', label: 'Run your morning, midday, evening plan', thread: 'E', weeklyTarget: 7 },
      { id: 'w11-workout', label: 'Strength workout', thread: 'W', weeklyTarget: 3 },
      { id: 'w11-walk', label: 'Walk', thread: 'W', weeklyTarget: 4 },
      { id: 'w11-bedtime', label: 'Bedtime within 30 minutes of plan', thread: 'R', weeklyTarget: 6 },
    ],
    toolSlugs: ['pattern-maintenance-system'],
    discussionPrompt: 'What pattern that used to own you is now under your control?',
  },
  {
    weekNumber: 12,
    blockId: 'EXCEL',
    title: 'Week 12: Celebration and Continuation',
    primaryFocus: 'Celebrate transformation. Plan continuation.',
    slideNotes: [
      'You did it. Transformation complete.',
      'Week 1 versus Week 12. The evidence.',
      'Your wins collection. Look at what you built.',
      "What's next: GST, Alumni, Round 2 options.",
      'Could you teach this? You are now the expert on you.',
      'This is who you are now, not what you do.',
    ],
    weekAtAGlance: [
      { id: 'w12-celebrate', label: 'Celebrate one specific win today', thread: 'O', weeklyTarget: 5 },
      { id: 'w12-reflect', label: 'Reflect on a Week 1 versus Week 12 difference', thread: 'P', weeklyTarget: 5 },
      { id: 'w12-plan-next', label: 'Take one step on the what is next plan', thread: 'O', weeklyTarget: 3 },
      { id: 'w12-workout', label: 'Strength workout', thread: 'W', weeklyTarget: 3 },
      { id: 'w12-walk', label: 'Walk', thread: 'W', weeklyTarget: 4 },
    ],
    toolSlugs: ['transformation-summary', 'whats-next-guide'],
    discussionPrompt: 'Share your biggest transformation. What changed for you?',
  },
];
