import { WorkoutExercise, WorkoutLibraryItem } from './workouts';

export const workoutLibrarySeed: WorkoutLibraryItem[] = [
  {
    cover_color: '#1F1F22',
    description: 'CREATE POWER · Foundations W1. Squat pattern + posterior chain.',
    difficulty: 'intermediate',
    duration_minutes: 30,
    equipment: ['dumbbells', 'bands'],
    exercises: [
      exercise('ex_1', 'Box Breathing Reset', 'bodyweight', 1, '60s', 0, true),
      exercise('ex_2', 'Goblet Squat', 'dumbbells', 4, '8-10', 90, false, 'Chest tall, knees track over toes.'),
      exercise('ex_3', 'DB Romanian Deadlift', 'dumbbells', 4, '8-10', 90),
      exercise('ex_4', 'Reverse Lunge', 'dumbbells', 3, '10 each leg', 75),
      exercise('ex_5', 'Glute Bridge', 'bodyweight', 3, '12-15', 60),
      exercise('ex_6', 'Banded Pall-Of Press', 'bands', 3, '10 each side', 45),
    ],
    focus_area: 'lower',
    id: 'seed-lower-body-a',
    name: 'Workout 1',
    order_index: 0,
  },
  {
    cover_color: '#1F1F22',
    description: 'CREATE POWER · Foundations W2. Horizontal push + pull primer.',
    difficulty: 'intermediate',
    duration_minutes: 30,
    equipment: ['dumbbells', 'bands'],
    exercises: [
      exercise('ex_1', 'Banded Pull-Apart', 'bands', 2, '10', 30, true),
      exercise('ex_2', 'DB Bench Press', 'dumbbells', 4, '8-10', 90),
      exercise('ex_3', 'DB One-Arm Row', 'dumbbells', 4, '10 each side', 75),
      exercise('ex_4', 'DB Push Press', 'dumbbells', 3, '8', 75),
      exercise('ex_5', 'Banded Face Pull', 'bands', 3, '12-15', 45),
      exercise('ex_6', 'Plank', 'bodyweight', 3, '30s hold', 30),
    ],
    focus_area: 'upper',
    id: 'seed-upper-body-a',
    name: 'Workout 2',
    order_index: 0,
  },
  {
    cover_color: '#1F1F22',
    description: 'CREATE POWER · Foundations W3. Hinge focus + single-leg stability.',
    difficulty: 'intermediate',
    duration_minutes: 30,
    equipment: ['dumbbells', 'bands'],
    exercises: [
      exercise('ex_1', 'World Greatest Stretch', 'bodyweight', 2, '4 each side', 30, true),
      exercise('ex_2', 'DB Deadlift', 'dumbbells', 4, '6-8', 120),
      exercise('ex_3', 'Bulgarian Split Squat', 'dumbbells', 3, '8 each leg', 90),
      exercise('ex_4', 'Single-Leg RDL', 'dumbbells', 3, '8 each leg', 75),
      exercise('ex_5', 'Hip Thrust', 'dumbbells', 3, '10-12', 60),
      exercise('ex_6', 'Bird Dog', 'bodyweight', 3, '8 each side', 30),
    ],
    focus_area: 'lower',
    id: 'seed-lower-body-b',
    name: 'Workout 3',
    order_index: 0,
  },
  {
    cover_color: '#1F1F22',
    description: 'CREATE POWER · Foundations W4. Vertical push + pull.',
    difficulty: 'intermediate',
    duration_minutes: 30,
    equipment: ['dumbbells', 'bands'],
    exercises: [
      exercise('ex_1', 'Cat-Cow', 'bodyweight', 2, '8 reps', 30, true),
      exercise('ex_2', 'DB Shoulder Press', 'dumbbells', 4, '8-10', 90),
      exercise('ex_3', 'Banded Lat Pulldown', 'bands', 4, '10-12', 75),
      exercise('ex_4', 'DB Incline Press', 'dumbbells', 3, '10', 75),
      exercise('ex_5', 'DB Bicep Curl', 'dumbbells', 3, '10-12', 60),
      exercise('ex_6', 'Dead Bug', 'bodyweight', 3, '6 each side', 30),
    ],
    focus_area: 'upper',
    id: 'seed-upper-body-b',
    name: 'Workout 4',
    order_index: 0,
  },
  {
    cover_color: '#1E5B45',
    description: 'Quick upper body builder. Push, pull, repeat.',
    difficulty: 'intermediate',
    duration_minutes: 30,
    equipment: ['dumbbells'],
    exercises: [
      exercise('ex_1', 'Push-Up', 'bodyweight', 3, '8-12', 60, true),
      exercise('ex_2', 'DB Bench Press', 'dumbbells', 4, '8-10', 90),
      exercise('ex_3', 'DB Row', 'dumbbells', 4, '10-12', 90),
      exercise('ex_4', 'DB Shoulder Press', 'dumbbells', 3, '10-12', 75),
      exercise('ex_5', 'DB Bicep Curl', 'dumbbells', 3, '12-15', 60),
    ],
    focus_area: 'upper',
    id: 'upper-body-pump-30',
    name: 'Upper Body Pump 30',
    order_index: 1,
  },
  {
    cover_color: '#D4A02A',
    description: 'Build lower body strength with the basics done well.',
    difficulty: 'beginner',
    duration_minutes: 45,
    equipment: ['dumbbells', 'bands'],
    exercises: [
      exercise('ex_1', 'Bodyweight Squat', 'bodyweight', 2, '10', 45, true),
      exercise('ex_2', 'Goblet Squat', 'dumbbells', 4, '8-10', 90, false, 'Keep chest tall, knees track over toes.'),
      exercise('ex_3', 'DB Romanian Deadlift', 'dumbbells', 4, '10-12', 90),
      exercise('ex_4', 'Reverse Lunge', 'dumbbells', 3, '10 each leg', 75),
      exercise('ex_5', 'Glute Bridge', 'bodyweight', 3, '15', 60),
    ],
    focus_area: 'lower',
    id: 'lower-body-foundations-45',
    name: 'Lower Body Foundations 45',
    order_index: 2,
  },
  {
    cover_color: '#B78219',
    description: 'Time-crunched but still want everything? This is it.',
    difficulty: 'intermediate',
    duration_minutes: 30,
    equipment: ['dumbbells'],
    exercises: [
      exercise('ex_1', 'DB Goblet Squat', 'dumbbells', 3, '10', 60),
      exercise('ex_2', 'DB Push Press', 'dumbbells', 3, '8', 75),
      exercise('ex_3', 'DB Row', 'dumbbells', 3, '10', 60),
      exercise('ex_4', 'DB Reverse Lunge', 'dumbbells', 3, '8 each leg', 60),
      exercise('ex_5', 'Plank', 'bodyweight', 3, '30s hold', 45),
    ],
    focus_area: 'full',
    id: 'full-body-30-express',
    name: 'Full Body 30 Express',
    order_index: 3,
  },
  {
    cover_color: '#1E5B45',
    description: 'For sore mornings, recovery days, or pre-workout flow.',
    difficulty: 'beginner',
    duration_minutes: 20,
    equipment: ['bodyweight', 'bands'],
    exercises: [
      exercise('ex_1', 'World Greatest Stretch', 'bodyweight', 2, '5 each side', 30),
      exercise('ex_2', 'Cat-Cow', 'bodyweight', 2, '10', 30),
      exercise('ex_3', 'Banded Pull-Apart', 'bands', 3, '15', 30),
      exercise('ex_4', '90/90 Hip Switch', 'bodyweight', 2, '10 each side', 30),
      exercise('ex_5', 'Down Dog to Cobra Flow', 'bodyweight', 2, '8 reps', 30),
    ],
    focus_area: 'mobility',
    id: 'mobility-reset-20',
    name: 'Mobility Reset 20',
    order_index: 4,
  },
  {
    cover_color: '#D4A02A',
    description: 'Short core circuit. Quality over quantity.',
    difficulty: 'beginner',
    duration_minutes: 15,
    equipment: ['bodyweight'],
    exercises: [
      exercise('ex_1', 'Dead Bug', 'bodyweight', 3, '8 each side', 30),
      exercise('ex_2', 'Bird Dog', 'bodyweight', 3, '10 each side', 30),
      exercise('ex_3', 'Side Plank', 'bodyweight', 2, '20s each side', 30),
      exercise('ex_4', 'Hollow Hold', 'bodyweight', 3, '20s', 30),
    ],
    focus_area: 'core',
    id: 'core-foundation-15',
    name: 'Core Foundation 15',
    order_index: 5,
  },
  {
    cover_color: '#B78219',
    description: 'Long session, heavy focus, pure strength work.',
    difficulty: 'advanced',
    duration_minutes: 60,
    equipment: ['dumbbells', 'barbell'],
    exercises: [
      exercise('ex_1', 'Barbell Back Squat', 'barbell', 5, '5', 150),
      exercise('ex_2', 'Barbell Bench Press', 'barbell', 5, '5', 150),
      exercise('ex_3', 'Bent-Over Row', 'barbell', 4, '6-8', 120),
      exercise('ex_4', 'DB Romanian Deadlift', 'dumbbells', 4, '8-10', 90),
      exercise('ex_5', 'Weighted Plank', 'bodyweight', 3, '45s', 60),
    ],
    focus_area: 'full',
    id: 'strength-builder-60',
    name: 'Strength Builder 60',
    order_index: 6,
  },
];

function exercise(
  id: string,
  name: string,
  equipment: string,
  target_sets: number,
  target_reps: string,
  rest_seconds: number,
  is_warmup = false,
  notes?: string,
): WorkoutExercise {
  return { equipment, id, is_warmup, name, notes, rest_seconds, target_reps, target_sets };
}
